
package com.viewds.wsdl.xacmlv3wd17pdp;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AuthorizationDecisionService", targetNamespace = "http://viewDS.com/wsdl/XACMLv3wd17PDP.wsdl", wsdlLocation = "file:/D:/EzAz/0viewds/XACMLv3WD17-PDP-workaround/XACMLv3wd17PDP-workaround.wsdl")
public class AuthorizationDecisionService
    extends Service
{

    private final static URL AUTHORIZATIONDECISIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.viewds.wsdl.xacmlv3wd17pdp.AuthorizationDecisionService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.viewds.wsdl.xacmlv3wd17pdp.AuthorizationDecisionService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/EzAz/0viewds/XACMLv3WD17-PDP-workaround/XACMLv3wd17PDP-workaround.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/EzAz/0viewds/XACMLv3WD17-PDP-workaround/XACMLv3wd17PDP-workaround.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AUTHORIZATIONDECISIONSERVICE_WSDL_LOCATION = url;
    }

    public AuthorizationDecisionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthorizationDecisionService() {
        super(AUTHORIZATIONDECISIONSERVICE_WSDL_LOCATION, new QName("http://viewDS.com/wsdl/XACMLv3wd17PDP.wsdl", "AuthorizationDecisionService"));
    }

    /**
     * 
     * @return
     *     returns AuthorizationDecisionPort
     */
    @WebEndpoint(name = "AuthorizationDecisionPort")
    public AuthorizationDecisionPort getAuthorizationDecisionPort() {
        return super.getPort(new QName("http://viewDS.com/wsdl/XACMLv3wd17PDP.wsdl", "AuthorizationDecisionPort"), AuthorizationDecisionPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthorizationDecisionPort
     */
    @WebEndpoint(name = "AuthorizationDecisionPort")
    public AuthorizationDecisionPort getAuthorizationDecisionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://viewDS.com/wsdl/XACMLv3wd17PDP.wsdl", "AuthorizationDecisionPort"), AuthorizationDecisionPort.class, features);
    }

}
