
package com.axiomatics.delegent.pdpsimple.v1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DelegentPDP", targetNamespace = "http://axiomatics.com/delegent/pdpsimple/v1", wsdlLocation = "file:/C:/Users/felix/workspace/EzAz-Java/drivers/DelegentPDP.xml")
public class DelegentPDP
    extends Service
{

    private final static URL DELEGENTPDP_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.axiomatics.delegent.pdpsimple.v1.DelegentPDP.class.getName());

    static {
        URL url = null;
	// url = new URL(baseUrl,
	// "file:/C:/Users/felix/git/ezaz/EzAz-Java/drivers/DelegentPDP.xml");
	url = com.axiomatics.delegent.pdpsimple.v1.DelegentPDP.class
		.getResource("/org/EzAz/Layer3Driver/Axiomatics/DelegentPDP.xml");
	URL url2=ClassLoader.getSystemResource("/org/EzAz/Layer3Driver/Axiomatics/DelegentPDP.xml");
        DELEGENTPDP_WSDL_LOCATION = url;
    }

    public DelegentPDP(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DelegentPDP() {
        super(DELEGENTPDP_WSDL_LOCATION, new QName("http://axiomatics.com/delegent/pdpsimple/v1", "DelegentPDP"));
    }

    /**
     * 
     * @return
     *     returns DelegentPDPPortType
     */
    @WebEndpoint(name = "DelegentPDPPort")
    public DelegentPDPPortType getDelegentPDPPort() {
        return super.getPort(new QName("http://axiomatics.com/delegent/pdpsimple/v1", "DelegentPDPPort"), DelegentPDPPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DelegentPDPPortType
     */
    @WebEndpoint(name = "DelegentPDPPort")
    public DelegentPDPPortType getDelegentPDPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://axiomatics.com/delegent/pdpsimple/v1", "DelegentPDPPort"), DelegentPDPPortType.class, features);
    }

}
